name: dev-machine

update:
  canaries: 1
  canary_watch_time: 10000-600000
  update_watch_time: 10000-600000
  max_in_flight: 1
  serial: true

instance_groups:
- name: dev-instance
  instances: 1
  azs: [z1]
  networks: [{name: default}]
  vm_type: small
  stemcell: default
  persistent_disk_type: 100GB
  jobs:
  - name: machine-setup
    release: dev-machine

variables: []

releases:
- name: dev-machine
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
